/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "tema1.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

req_authorization_return *
req_auth_1(char **argp, CLIENT *clnt)
{
	static req_authorization_return clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REQ_AUTH,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_req_authorization_return, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

req_access_return *
req_access_1(req_access_param *argp, CLIENT *clnt)
{
	static req_access_return clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REQ_ACCESS,
		(xdrproc_t) xdr_req_access_param, (caddr_t) argp,
		(xdrproc_t) xdr_req_access_return, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

validate_action_return *
validate_action_1(action_param *argp, CLIENT *clnt)
{
	static validate_action_return clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, VALIDATE_ACTION,
		(xdrproc_t) xdr_action_param, (caddr_t) argp,
		(xdrproc_t) xdr_validate_action_return, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

approve_req_token_return *
approve_token_1(char **argp, CLIENT *clnt)
{
	static approve_req_token_return clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, APPROVE_TOKEN,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_approve_req_token_return, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

req_access_refresh_return *
req_access_refr_1(req_access_param *argp, CLIENT *clnt)
{
	static req_access_refresh_return clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REQ_ACCESS_REFR,
		(xdrproc_t) xdr_req_access_param, (caddr_t) argp,
		(xdrproc_t) xdr_req_access_refresh_return, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
