/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"

bool_t
xdr_req_authorization_return (XDR *xdrs, req_authorization_return *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->approved))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_access_param (XDR *xdrs, req_access_param *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_access_return (XDR *xdrs, req_access_return *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_access_refresh_return (XDR *xdrs, req_access_refresh_return *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->auth_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_action_param (XDR *xdrs, action_param *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation_type, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_action_return (XDR *xdrs, validate_action_return *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id_client, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->acces_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->result, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_req_token_return (XDR *xdrs, approve_req_token_return *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->permisions, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->approved))
		 return FALSE;
	return TRUE;
}
