/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.h"


void
tema1prog_1(char *host)
{
	CLIENT *clnt;
	req_authorization_return  *result_1;
	char * req_auth_1_arg;
	req_access_return  *result_2;
	req_access_param  req_access_1_arg;
	char * *result_3;
	action_param  validate_action_1_arg;
	approve_req_token_return  *result_4;
	char * approve_token_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TEMA1PROG, TEMA1VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = req_auth_1(&req_auth_1_arg, clnt);
	if (result_1 == (req_authorization_return *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = req_access_1(&req_access_1_arg, clnt);
	if (result_2 == (req_access_return *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = validate_action_1(&validate_action_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = approve_token_1(&approve_token_1_arg, clnt);
	if (result_4 == (approve_req_token_return *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	tema1prog_1 (host);
exit (0);
}
