/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
tema1prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *req_auth_1_arg;
		req_access_param req_access_1_arg;
		action_param validate_action_1_arg;
		char *approve_token_1_arg;
		req_access_param req_access_refr_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQ_AUTH:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_req_authorization_return;
		local = (char *(*)(char *, struct svc_req *)) req_auth_1_svc;
		break;

	case REQ_ACCESS:
		_xdr_argument = (xdrproc_t) xdr_req_access_param;
		_xdr_result = (xdrproc_t) xdr_req_access_return;
		local = (char *(*)(char *, struct svc_req *)) req_access_1_svc;
		break;

	case VALIDATE_ACTION:
		_xdr_argument = (xdrproc_t) xdr_action_param;
		_xdr_result = (xdrproc_t) xdr_validate_action_return;
		local = (char *(*)(char *, struct svc_req *)) validate_action_1_svc;
		break;

	case APPROVE_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_approve_req_token_return;
		local = (char *(*)(char *, struct svc_req *)) approve_token_1_svc;
		break;

	case REQ_ACCESS_REFR:
		_xdr_argument = (xdrproc_t) xdr_req_access_param;
		_xdr_result = (xdrproc_t) xdr_req_access_refresh_return;
		local = (char *(*)(char *, struct svc_req *)) req_access_refr_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

extern void init_server(int argc, char **argv);

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TEMA1PROG, TEMA1VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TEMA1PROG, TEMA1VERS, tema1prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TEMA1PROG, TEMA1VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TEMA1PROG, TEMA1VERS, tema1prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TEMA1PROG, TEMA1VERS, tcp).");
		exit(1);
	}
	
	init_server(argc, argv);
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
